{
 "title": "Monitoramento Hackaton Agro",
 "tags": [
  "kubernetes",
  "hackaton"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Serviços Online (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status Detalhado por Serviço",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Latência de Coleta (Scrape Duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  }
 ]
}